server:
 port: 8181
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: ${DB_PASSWORD:root}
    password: ${DB_PASSWORD:P@ssword}
    
   


  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
debug: true