spring:
  application:
    name: hr-service
server:
 port: 8280
 
eureka:
   client:
     register-with-eureka: true
     fetch-registry: true
     service-url:
       defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

resilience4j:
  circuitbreaker:
    instances:
     hr-service-cb:
       registerHealthIndicator: true
       slidingWindowSize: 10
       permittedNumberOfCallsInHalfOpenState: 3
       slidingWindowType: COUNT_BASED
       minimumNumberOfCalls: 2
       waitDurationInOpenState: 10s
       failureRateThreshold: 33.3
       automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health: 
   circuitbreakers:
      enabled: true
emp:
 service:
  uri: http://emp-service/emp/
